select years.cset_id,
       all_categories.wos_id,
       all_categories.ds_id,
       all_categories.mag_id,
       years.year,
       all_countries.country,
       all_categories.wos_subject,
       all_categories.ds_subject,
       all_categories.mag_subject,
       citation_counts.min_times_cited,
       citation_counts.times_cited,
       citation_counts.ds_times_cited,
       citation_counts.wos_times_cited,
       citation_counts.mag_times_cited,
       all_predictions.arxiv_coverage,
       all_predictions.keyword_hit,
       all_predictions.elsevier_hit,
       all_predictions.subject_hit,
       all_predictions.scibert_hit,
       all_predictions.scibert_cl_hit,
       all_predictions.scibert_cv_hit,
       all_predictions.scibert_ro_hit,
       all_predictions.scibert_not_cv_hit,
       all_predictions.arxiv_scibert_hit,
       all_predictions.arxiv_scibert_cl_hit,
       all_predictions.arxiv_scibert_cv_hit,
       all_predictions.arxiv_scibert_ro_hit,
       all_predictions.arxiv_scibert_not_cv_hit,
       percentiles.percentile,
       percentiles.keyword_percentile,
       percentiles.elsevier_percentile,
       percentiles.subject_percentile,
       percentiles.scibert_percentile,
       percentiles.scibert_cv_percentile,
       percentiles.scibert_cl_percentile,
       percentiles.scibert_ro_percentile,
       percentiles.scibert_not_cv_percentile,
       percentiles.arxiv_scibert_percentile,
       percentiles.arxiv_scibert_cv_percentile,
       percentiles.arxiv_scibert_cl_percentile,
       percentiles.arxiv_scibert_ro_percentile,
       percentiles.arxiv_scibert_not_cv_percentile,
       -- Minimum-citation percentiles
       percentiles.min_percentile,
       percentiles.keyword_min_percentile,
       percentiles.elsevier_min_percentile,
       percentiles.scibert_min_percentile,
       percentiles.scibert_cv_min_percentile,
       percentiles.scibert_cl_min_percentile,
       percentiles.scibert_ro_min_percentile,
       percentiles.scibert_not_cv_min_percentile,
       percentiles.arxiv_scibert_min_percentile,
       percentiles.arxiv_scibert_cv_min_percentile,
       percentiles.arxiv_scibert_cl_min_percentile,
       percentiles.arxiv_scibert_ro_min_percentile,
       percentiles.arxiv_scibert_not_cv_min_percentile,
       -- DS citation percentiles
       ds_percentiles.ds_percentile,
       ds_percentiles.ds_keyword_percentile,
       ds_percentiles.ds_elsevier_percentile,
       ds_percentiles.ds_scibert_percentile,
       ds_percentiles.ds_scibert_cv_percentile,
       ds_percentiles.ds_scibert_cl_percentile,
       ds_percentiles.ds_scibert_ro_percentile,
       ds_percentiles.ds_scibert_not_cv_percentile,
       ds_percentiles.ds_arxiv_scibert_percentile,
       ds_percentiles.ds_arxiv_scibert_cv_percentile,
       ds_percentiles.ds_arxiv_scibert_cl_percentile,
       ds_percentiles.ds_arxiv_scibert_ro_percentile,
       ds_percentiles.ds_arxiv_scibert_not_cv_percentile,
       -- MAG citation percentiles
       mag_percentiles.mag_percentile,
       mag_percentiles.mag_keyword_percentile,
       mag_percentiles.mag_elsevier_percentile,
       mag_percentiles.mag_scibert_percentile,
       mag_percentiles.mag_scibert_cv_percentile,
       mag_percentiles.mag_scibert_cl_percentile,
       mag_percentiles.mag_scibert_ro_percentile,
       mag_percentiles.mag_scibert_not_cv_percentile,
       mag_percentiles.mag_arxiv_scibert_percentile,
       mag_percentiles.mag_arxiv_scibert_cv_percentile,
       mag_percentiles.mag_arxiv_scibert_cl_percentile,
       mag_percentiles.mag_arxiv_scibert_ro_percentile,
       mag_percentiles.mag_arxiv_scibert_not_cv_percentile,
       -- WOS citation percentiles
       wos_percentiles.wos_percentile,
       wos_percentiles.wos_keyword_percentile,
       wos_percentiles.wos_elsevier_percentile,
       wos_percentiles.wos_scibert_percentile,
       wos_percentiles.wos_scibert_cv_percentile,
       wos_percentiles.wos_scibert_cl_percentile,
       wos_percentiles.wos_scibert_ro_percentile,
       wos_percentiles.wos_scibert_not_cv_percentile,
       wos_percentiles.wos_arxiv_scibert_percentile,
       wos_percentiles.wos_arxiv_scibert_cv_percentile,
       wos_percentiles.wos_arxiv_scibert_cl_percentile,
       wos_percentiles.wos_arxiv_scibert_ro_percentile,
       wos_percentiles.wos_arxiv_scibert_not_cv_percentile
from oecd.all_years years
         left join oecd.all_citation_counts citation_counts
                   on citation_counts.cset_id = years.cset_id
         left join oecd.all_predictions all_predictions on all_predictions.cset_id = years.cset_id
         left join oecd.all_countries all_countries on all_countries.cset_id = years.cset_id
         left join oecd.percentiles on percentiles.cset_id = years.cset_id
         left join oecd.all_categories on all_categories.cset_id = years.cset_id
         left join oecd.ds_percentiles on ds_percentiles.cset_id = years.cset_id
         left join oecd.mag_percentiles on mag_percentiles.cset_id = years.cset_id
         left join oecd.wos_percentiles on wos_percentiles.cset_id = years.cset_id
